pipeline {
    agent any

    environment {
        DOCKER_IMAGE_PREFIX = 'nthheulwen'
        GITOPS_REPO = 'https://github.com/huyen-nguyen-04/DevOps-Project-2-CD.git'
        CREDENTIAL_ID = 'Github-PAT'
    }

    stages {
        stage('Get Tag Name') {
            steps {
                script {
                    TAG_NAME = sh(script: 'git describe --tags --exact-match', returnStdout: true).trim()
                }
            }
        }

        stage('Build Docker Images') {
            steps {
                script {
                    sh """
                        ./mvnw clean install \
                            -f pom.xml \
                            -P buildDocker \
                            -Ddocker.image.prefix=${DOCKER_IMAGE_PREFIX} \
                            -Ddocker.image.tag=${TAG_NAME} 
                    """
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                script {
                    SERVICES = [
                        'spring-petclinic-api-gateway',
                        'spring-petclinic-config-server',
                        'spring-petclinic-customers-service',
                        'spring-petclinic-vets-service',
                        'spring-petclinic-visits-service'
                    ]

                    PUSH_STAGES = [:]
                    for (service in SERVICES) {
                        PUSH_STAGES["Push ${service}"] = {
                            stage("Push ${service}") {
                                script {
                                    image = "${DOCKER_IMAGE_PREFIX}/${service}:${TAG_NAME}"
                                    sh "docker push ${image}"
                                    echo "Docker image ${image} pushed successfully."
                                }
                            }
                        }
                    }

                    parallel PUSH_STAGES
                }
            }
        }

        stage('Update GitOps Repository') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'Github-PAT', usernameVariable: 'GIT_USER', passwordVariable: 'GIT_PASSWORD')]) {
                    sh '''
                        rm -rf DevOps-Project-2-CD
                        git clone https://$GIT_USER:$GIT_PASSWORD@github.com/huyen-nguyen-04/DevOps-Project-2-CD.git --depth 1
                        cd DevOps-Project-2-CD
                        git checkout main
                        sed -i 's/tag: .*/tag: ${TAG_NAME/g' staging/values.yaml
                        sed -i 's/tag: .*/tag: ${TAG_NAME/g' dev/values.yaml
                        git add .
                        git commit -m "Update image tag to ${TAG_NAME"
                        git push origin main
                    '''
                }
            }
        }

    }
}
